Install WiRoc services and all into the image, only set root/chip user password, generate locale at first run

diff --git a/userpatches/overlay/armbian-firstlogin b/userpatches/overlay/armbian-firstlogin
--- a/userpatches/overlay/armbian-firstlogin
+++ b/userpatches/overlay/armbian-firstlogin
@@ -265,7 +265,210 @@ set_shell() {
 }
 
 set_timezone_and_locales() {
-	LOCALES=$PRESET_LOCALE
+
+	# Grab this machine's public IP address
+	PUBLIC_IP=$(curl --max-time 5 -s https://ipinfo.io/ip)
+
+	# Check if we have wireless adaptor
+	WIFI_DEVICE=$(LC_ALL=C iw dev | awk '$1=="Interface"{print $2}' 2> /dev/null)
+
+	if [ -z "$PUBLIC_IP" ]; then
+
+		# ask for connecting to wireless if wifi device is found
+		if [[ -n "$WIFI_DEVICE" ]]; then
+			echo -e "Internet connection was \x1B[91mnot detected\x1B[0m."
+			echo ""
+			unset response
+			while [[ ! "${response}" =~ ^(Y|y|N|n)$ ]]; do
+				if [ -z $PRESET_CONNECT_WIRELESS ];then
+					read -r -p "Connect via wireless? [Y/n] " response
+					response=${response:-Y}
+				else
+					response=n
+				fi
+			done
+			if [[ "${response}" =~ ^(Y|y)$ ]]; then
+
+				# We could have multiple devices
+				if (( $(grep -c . <<<"$WIFI_DEVICE") > 1 )); then
+					scanning=0
+					while [[ ${scanning} -lt 3 ]]; do
+						scanning=$(( scanning + 1 ))
+						echo -e "\nMultiple wireless adaptors detected. Choose primary:\n"
+						WIFI_DEVICES=($(printf '%s\n' "${WIFI_DEVICE[@]}" | sed 's/^[ \t]*//' | sed 's/"//g' | sed 's/ESSID://' | awk 'BEGIN{FS=OFS=","} {$NF=++count OFS $NF} 1'))
+						for str in ${WIFI_DEVICES[@]}; do echo $str | sed "s/,/ \t /g"; done
+						echo ""
+						read -r -p "Enter a number of wireles adaptor: " input
+						if [[ "$input" =~ ^[0-9]{,2}$ && -n "$input" ]] ; then break; fi
+					done
+					[[ -z $input ]] && input=1
+					WIFI_DEVICE=$(echo ${WIFI_DEVICES[$input-1]} | cut -d"," -f2)
+				fi
+
+				# bring up wifi device (not done by networkd, only by NetworkManager)
+				ip link set ${WIFI_DEVICE} up
+				# get list of wireless networks
+				scanning=0
+				broken=1
+				while [[ ${scanning} -lt 3 ]]; do
+					sleep 0.5
+					scanning=$(( scanning + 1 ))
+					readarray -t ARRAY < <(iw dev ${WIFI_DEVICE} scan 2> /dev/null | egrep 'SSID' | sed 's/^[ \t]*//' | sed 's/"//g' | sed 's/SSID: //' | sed '/^$/d' | sort | uniq | awk 'BEGIN{FS=OFS=","} {$NF=++count OFS $NF} 1')
+					if [[ ${#ARRAY[@]} -gt 0 ]]; then broken=0; break; fi
+				done
+				# wifi can also fail
+				if [[ ${broken} == 1 ]]; then
+					echo -e "\nWireless connection was \x1B[91mnot detected\x1B[0m.\n"
+				else
+					echo -e "\nDetected wireless networks:\n"
+					scanning=0
+					broken=1
+					while [[ ${scanning} -lt 3 ]]; do
+						scanning=$(( scanning + 1 ))
+						while [[ 1 ]] ; do
+							for str in "${ARRAY[@]}"; do echo $str | sed "s/,/ \t /"; done
+							echo ""
+							read -r -p "Enter a number of SSID: " input
+							if [[ "$input" =~ ^[0-9]{,2}$ ]] ; then break; fi
+						done
+						# get password
+						while [[ -n "${input}" ]] ; do
+							SSID=$(echo ${ARRAY[$input-1]} | cut -d"," -f2-)
+							echo ""
+							read -r -p "Enter a password for ${SSID}: " password
+							break
+						done
+
+						# generate config
+						cat <<- EOF > /etc/netplan/30-wifis-dhcp.yaml
+						# Created by Armbian firstlogin script
+						network:
+						  wifis:
+						    ${WIFI_DEVICE}:
+						      dhcp4: yes
+						      dhcp6: yes
+						      access-points:
+						        "$SSID":
+						         password: "${password}"
+						EOF
+						chmod 600 /etc/netplan/30-wifis-dhcp.yaml
+
+						# apply to netplan
+						systemctl daemon-reload
+						netplan apply --timeout 0 2>/dev/null
+
+						# wireless link probing
+						pinging=10
+						broken=1
+						WIRELESSLINK=""
+						echo ""
+						while [[ ${pinging} -gt 1 && -n "${input}" && -n "${password}" ]]; do
+							pinging=$(( pinging - 1 ))
+							printf "\rProbing wireless link ($pinging)"
+							WIRELESSLINK=$(iw "${WIFI_DEVICE}" link 2> /dev/null | grep "$SSID")
+							sleep 2
+							# exit if connection is suffesful
+							if [[ "${WIRELESSLINK}" == *$SSID* ]]; then
+								broken=0
+								break
+							fi
+						done
+
+						if [[ ${broken} == 1 ]]; then
+							echo -e "\n\nWireless link was \x1B[91mnot detected\x1B[0m. Wrong password or weak signal."
+						fi
+						# get public IP probing
+						broken=1
+						pinging=10
+
+						while [[ ${pinging} -gt 1 && -n "${input}" && -n "${password}" && "${WIRELESSLINK}" == *$SSID* ]]; do
+							pinging=$(( pinging - 1 ))
+							printf "\rProbing internet connection ($pinging)"
+							PUBLIC_IP=$(curl --max-time 5 -s https://ipinfo.io/ip)
+							if [[ -n "$PUBLIC_IP" ]]; then
+								broken=0
+								break
+							else
+								sleep 5
+							fi
+						done
+						echo ""
+
+						if [[ ${broken} == 0 ]]; then
+							break
+						fi
+					done
+
+						if [[ ${broken} == 1 ]]; then
+							echo -e "\n\x1B[91mUnable to connect to Access Point\x1B[0m.\n"
+							rm -f /etc/netplan/30-wifis-dhcp.yaml
+							netplan apply --timeout 0 2>/dev/null
+							systemctl daemon-reload
+						fi
+
+				fi # detected or not detected wireless network
+			fi
+			echo ""
+		fi
+	fi
+
+	# Grab IP once again if not found
+	sleep 3
+	[[ -z "$PUBLIC_IP" && -n "$WIFI_DEVICE" ]] && PUBLIC_IP=$(curl --max-time 5 -s https://ipinfo.io/ip)
+
+	# Call the geolocation API and capture the output
+	RES=$(
+		curl --max-time 5 -s "http://ipwhois.app/json/${PUBLIC_IP}" |
+			jq '.timezone, .country, .country_code' |
+			while read -r TIMEZONE; do
+				read -r COUNTRY
+				echo "${TIMEZONE},${COUNTRY},${COUNTRYCODE}" | tr --delete '"\n'
+			done
+	)
+
+	TZDATA=$(echo "${RES}" | cut -d"," -f1)
+	CCODE=$(echo "${RES}" | cut -d"," -f3 | xargs)
+
+	unset response
+	while [[ ! "${response}" =~ ^(Y|y|N|n)$ ]]; do
+		if [ -z "${SET_LANG_BASED_ON_LOCATION}" ] && [ -n "${TZDATA}" ];then
+			echo -e "Detected timezone: \x1B[92m$TZDATA\x1B[0m"
+			echo ""
+			read -r -p "Set user language based on your location? [Y/n] " response
+			response=${response:-Y}
+		else
+			response=$SET_LANG_BASED_ON_LOCATION
+			break
+		fi
+	done
+	# change it only if we have a match and if we agree
+	if [[ "${response}" =~ ^(N|n)$ ]]; then
+		unset CCODE TZDATA
+	fi
+
+	LOCALES=$(grep territory /usr/share/i18n/locales/* | grep _"$CCODE" | cut -d ":" -f 1 | cut -d "/" -f 6 |
+		xargs -I{} grep {} /usr/share/i18n/SUPPORTED | grep "UTF-8$" | cut -d " " -f 1)
+	# UTF8 is not present everywhere so check again in case it returns empty value
+	[[ -z "$LOCALES" ]] && LOCALES=$(grep territory /usr/share/i18n/locales/* | grep _"$CCODE" | cut -d ":" -f 1 | cut -d "/" -f 6 |
+		xargs -I{} grep {} /usr/share/i18n/SUPPORTED | cut -d " " -f 1)
+	readarray -t options <<< "${LOCALES}"
+
+	if [ -z $PRESET_LOCALE ];then
+		# when having more locales, prompt for choosing one
+		if [[ "${#options[@]}" -gt 1 ]]; then
+			options+=("Skip generating locales")
+			echo -e "\nAt your location, more locales are possible:\n"
+			PS3='Please enter your choice:'
+			select opt in "${options[@]}"; do
+				if [[ " ${options[*]} " == *" ${opt} "* ]]; then
+					LOCALES=${opt}
+					break
+				fi
+			done
+		fi
+	else
+		LOCALES=$PRESET_LOCALE
+	fi
 
 	if [[ "${LOCALES}" != *Skip* ]]; then
 
@@ -332,6 +535,9 @@ add_profile_sync_settings() {
 add_user() {
 	read -r -t 0 _
 	REPEATS=3
+	# WiRoc: the 'chip' user is pre-created (locked) at build time. Track whether
+	# it already exists so we skip adduser/home creation and only set its password.
+	USER_EXISTS=0
 	while [ -f "/root/.not_logged_in_yet" ]; do
 		[[ -z "${PRESET_USER_NAME}" ]] && echo -e "\nPlease provide a username (eg. your first name): \c"
 		if [ -z "$PRESET_USER_NAME" ];then
@@ -346,7 +552,11 @@ add_user() {
 
 		RealUserName="$(echo "$username" | tr '[:upper:]' '[:lower:]' | tr -d -c '[:alnum:]')"
 		[ -z "$RealUserName" ] && return
-		if ! id "$RealUserName" > /dev/null 2>&1; then break; else echo -e "Username \e[0;31m$RealUserName\x1B[0m already exists on the system."; fi
+		if id "$RealUserName" > /dev/null 2>&1; then
+			USER_EXISTS=1
+			echo -e "User \e[0;92m$RealUserName\x1B[0m already exists; setting its password."
+		fi
+		break
 	done
 
 	while [ -f "/root/.not_logged_in_yet" ]; do
@@ -380,7 +590,9 @@ add_user() {
 				RealName="$PRESET_DEFAULT_REALNAME"
 			fi
 
-			adduser --quiet --disabled-password --home /home/"$RealUserName" --gecos "$RealName" "$RealUserName"
+			if [[ "$USER_EXISTS" -eq 0 ]]; then
+				adduser --quiet --disabled-password --home /home/"$RealUserName" --gecos "$RealName" "$RealUserName"
+			fi
 
 			# download and add SSH key if defined
 			if [[ -n "${PRESET_USER_KEY}" ]]; then
@@ -408,13 +620,7 @@ add_user() {
 			[ -z "$RealName" ] && RealName="$RealUserName"
 			echo -e "\nDear \e[0;92m${RealName}\x1B[0m, your account \e[0;92m${RealUserName}\x1B[0m has been created and is sudo enabled."
 			echo -e "Please use this account for your daily work from now on.\n"
-			
 			rm -f /root/.not_logged_in_yet
-			# disable autologin
-			rm -f /etc/systemd/system/getty@.service.d/override.conf
-			rm -f /etc/systemd/system/serial-getty@.service.d/override.conf
-			systemctl daemon-reload
-
 			# set up profile sync daemon on desktop systems
 			if command -v psd > /dev/null 2>&1; then
 				echo -e "${RealUserName} ALL=(ALL) NOPASSWD: /usr/bin/psd-overlay-helper" >> /etc/sudoers
@@ -443,10 +649,9 @@ if [[ -f /root/.not_logged_in_yet && -n $(tty) ]]; then
 	do_firstrun_automated_network_configuration
 
 	# disable autologin
-	# moved to add user
-	#rm -f /etc/systemd/system/getty@.service.d/override.conf
-	#rm -f /etc/systemd/system/serial-getty@.service.d/override.conf
-	#systemctl daemon-reload
+	rm -f /etc/systemd/system/getty@.service.d/override.conf
+	rm -f /etc/systemd/system/serial-getty@.service.d/override.conf
+	systemctl daemon-reload
 
 	declare desktop_dm="none"
 	declare -i desktop_is_sddm=0 desktop_is_lightdm=0 desktop_is_gdm3=0
@@ -645,18 +850,156 @@ if [[ -f /root/.not_logged_in_yet && -n $(tty) ]]; then
 	# restart sshd daemon
 	systemctl restart ssh.service
 
-	# no display manager detected -> clear screen and show motd
-	clear
-	run-parts --lsbsysinit /etc/update-motd.d
+	# rpardini: hacks per-dm, very much legacy stuff that works by a miracle
+	if [[ "${desktop_dm}" == "lightdm" ]] && [ -n "$RealName" ]; then
 
-	# Display reboot recommendation if necessary
-	if [[ -f /var/run/resize2fs-reboot ]]; then
-		printf "\n\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
-		printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
+		mkdir -p /etc/lightdm/lightdm.conf.d
+		cat <<- EOF > /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+			[Seat:*]
+			autologin-user=$RealUserName
+			autologin-user-timeout=0
+			user-session=xfce
+		EOF
+
+		# select gnome session (has to be first or it breaks budgie/cinnamon desktop autologin and user-session)
+		# @TODO: remove this, gnome should use gdm3, not lightdm
+		[[ -x $(command -v gnome-session) ]] && sed -i "s/user-session.*/user-session=ubuntu/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+		[[ -x $(command -v gnome-session) ]] && sed -i "s/user-session.*/user-session=ubuntu/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+
+		# select awesome session
+		[[ -x $(command -v awesome) ]] && sed -i "s/user-session.*/user-session=awesome/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+		[[ -x $(command -v awesome) ]] && sed -i "s/user-session.*/user-session=awesome/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+
+		# select budgie session
+		[[ -x $(command -v budgie-desktop) ]] && sed -i "s/user-session.*/user-session=budgie-desktop/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+		[[ -x $(command -v budgie-desktop) ]] && sed -i "s/user-session.*/user-session=budgie-desktop/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+
+		# select cinnamon session
+		[[ -x $(command -v cinnamon) ]] && sed -i "s/user-session.*/user-session=cinnamon/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+		[[ -x $(command -v cinnamon) ]] && sed -i "s/user-session.*/user-session=cinnamon/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+
+		# select deepin session
+		[[ -x $(command -v deepin-wm) ]] && sed -i "s/user-session.*/user-session=deepin/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+		[[ -x $(command -v deepin-wm) ]] && sed -i "s/user-session.*/user-session=deepin/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+
+		# select ice-wm session
+		[[ -x $(command -v icewm-session) ]] && sed -i "s/user-session.*/user-session=icewm-session/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+		[[ -x $(command -v icewm-session) ]] && sed -i "s/user-session.*/user-session=icewm-session/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+
+		# select i3 session
+		[[ -x $(command -v i3) ]] && sed -i "s/user-session.*/user-session=i3/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+		[[ -x $(command -v i3) ]] && sed -i "s/user-session.*/user-session=i3/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+
+		# select lxde session
+		[[ -x $(command -v startlxde) ]] && sed -i "s/user-session.*/user-session=LXDE/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+		[[ -x $(command -v startlxde) ]] && sed -i "s/user-session.*/user-session=LXDE/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+
+		# select lxqt session
+		[[ -x $(command -v startlxqt) ]] && sed -i "s/user-session.*/user-session=lxqt/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+		[[ -x $(command -v startlxqt) ]] && sed -i "s/user-session.*/user-session=lxqt/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+
+		# select mate session
+		[[ -x $(command -v mate-wm) ]] && sed -i "s/user-session.*/user-session=mate/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+		[[ -x $(command -v mate-wm) ]] && sed -i "s/user-session.*/user-session=mate/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+
+		# select sway wayland session
+		[[ -x $(command -v sway) ]] && sed -i "s/user-session.*/user-session=sway/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+		[[ -x $(command -v sway) ]] && sed -i "s/user-session.*/user-session=sway/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+
+		# select xmonad session
+		[[ -x $(command -v xmonad) ]] && sed -i "s/user-session.*/user-session=xmonad/" /etc/lightdm/lightdm.conf.d/11-armbian.conf
+		[[ -x $(command -v xmonad) ]] && sed -i "s/user-session.*/user-session=xmonad/" /etc/lightdm/lightdm.conf.d/22-armbian-autologin.conf
+
+		ln -sf /lib/systemd/system/lightdm.service /etc/systemd/system/display-manager.service
+
+		if [[ -f /var/run/resize2fs-reboot ]]; then
+			# Let the user reboot now otherwise start desktop environment
+			printf "\n\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
+			printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
+		else
+			echo -e "\n\e[1m\e[39mNow starting desktop environment...\x1B[0m\n"
+			sleep 1
+			service lightdm start 2> /dev/null
+			if [ -f /root/.desktop_autologin ]; then
+				rm /root/.desktop_autologin
+			else
+				systemctl -q enable armbian-disable-autologin.timer
+				systemctl start armbian-disable-autologin.timer
+			fi
+			# logout if logged at console
+			who -la | grep root | grep -q tty1 && exit 1
+		fi
+
+	elif [[ "${desktop_dm}" == "gdm3" ]] && [ -n "$RealName" ]; then
+		# 1st run goes without login
+		mkdir -p /etc/gdm3
+		cat <<- EOF > /etc/gdm3/custom.conf
+			[daemon]
+			AutomaticLoginEnable = true
+			AutomaticLogin = $RealUserName
+		EOF
+
+		ln -sf /lib/systemd/system/gdm3.service /etc/systemd/system/display-manager.service
+
+		if [[ -f /var/run/resize2fs-reboot ]]; then
+			# Let the user reboot now otherwise start desktop environment
+			printf "\n\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
+			printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
+		else
+			echo -e "\n\e[1m\e[39mNow starting desktop environment...\x1B[0m\n"
+			sleep 1
+			service gdm3 start 2> /dev/null
+			if [ -f /root/.desktop_autologin ]; then
+				rm /root/.desktop_autologin
+			else
+				(
+					sleep 20
+					sed -i "s/AutomaticLoginEnable.*/AutomaticLoginEnable = false/" /etc/gdm3/custom.conf
+				) &
+			fi
+			# logout if logged at console
+			who -la | grep root | grep -q tty1 && exit 1
+		fi
+	elif [[ "${desktop_dm}" == "sddm" ]] && [ -n "$RealName" ]; then
+
+		# create default sddm config
+		mkdir -p /etc/sddm.conf.d
+
+		if [ ! -e "/etc/sddm.conf.d/armbian.conf" ]; then
+			cat <<- EOF > /etc/sddm.conf.d/armbian.conf
+				[Theme]
+				Current=breeze
+				[General]
+				InputMethod=none
+			EOF
+		fi
+
+		# 1st run goes without login
+		cat <<- EOF > /etc/sddm.conf.d/autologin.conf
+			[Autologin]
+			User=$RealUserName
+		EOF
+		echo -e "\n\e[1m\e[39mNow starting desktop environment via ${desktop_dm}...\x1B[0m\n"
+		systemctl enable --now sddm 2> /dev/null
+
+		if [ -f /root/.desktop_autologin ]; then
+				rm /root/.desktop_autologin
+		else
+			systemctl -q enable armbian-disable-autologin.timer
+		fi
+		# logout if logged at console
+		who -la | grep root | grep -q tty1 && exit 1
+
+	else
+		# no display manager detected -> clear screen and show motd
+		clear
+		run-parts --lsbsysinit /etc/update-motd.d
+
+		# Display reboot recommendation if necessary
+		if [[ -f /var/run/resize2fs-reboot ]]; then
+			printf "\n\n\e[0;91mWarning: a reboot is needed to finish resizing the filesystem \x1B[0m \n"
+			printf "\e[0;91mPlease reboot the system now \x1B[0m \n\n"
+		fi
+
 	fi
-fi
-
-# Run provisioning script if exists
-if [[ -f /root/provisioning.sh ]]; then
-	. /root/provisioning.sh
 fi
